# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

jets = Team.create({location: 'New York',			name: 'Jets'})
dolphins = Team.create({location: 'Miami',				name: 'Dolphins'})
patriots = Team.create({location: 'New England', 	name: 'Patriots'})
bills = Team.create({location: 'Buffalo',			name: 'Bills'})
giants = Team.create({location: 'New York', 		name: 'Giants'})
eagles = Team.create({location: 'Philadelphia',	name: 'Eagles'})
cowboys = Team.create({location: 'Dallas',				name: 'Cowboys'})
redskins = Team.create({location: 'Washington',		name: 'Redskins'})
steelers = Team.create({location: 'Pittsburg',		name: 'Steelers'})
bengals = Team.create({location: 'Cincinnatti',	name: 'Bengals'})
browns = Team.create({location: 'Cleveland',		name: 'Browns'})
ravens = Team.create({location: 'Baltimore',		name: 'Ravens'})
packers = Team.create({location: 'Green Bay',		name: 'Packers'})
bears = Team.create({location: 'Chicago',			name: 'Bears'})
lions = Team.create({location: 'Detroit',			name: 'Lions'})
vikings = Team.create({location: 'Minnesota',		name: 'Vikings'})
colts = Team.create({location: 'Indianapolis',	name: 'Colts'})
jaguars = Team.create({location: 'Jacksonville',	name: 'Jaguars'})
titans = Team.create({location: 'Tennessee',		name: 'Titans'})
texans = Team.create({location: 'Houston',			name: 'Texans'})
buccaneers = Team.create({location: 'Tamba Bay',		name: 'Buccaneers'})
falcons = Team.create({location: 'Atlanta',			name: 'Falcons'})
saints = Team.create({location: 'New Orleans',	name: 'Saints'})
panthers = Team.create({location: 'Carolina',			name: 'Panthers'})
chiefs = Team.create({location: 'Kansas City',	name: 'Chiefs'})
broncos = Team.create({location: 'Denver',				name: 'Broncos'})
chargers = Team.create({location: 'San Diego',		name: 'Chargers'})
raiders = Team.create({location: 'Oakland',			name: 'Raiders'})
fortyniners = Team.create({location: 'San Francisco',name: '49ers'})
seahawks = Team.create({location: 'Seattle',			name: 'Seahawks'})
rams = Team.create({location: 'St. Louis',		name: 'Rams'})
cardinals = Team.create({location: 'Arizona',			name: 'Cardinals'})
bye = Team.create({location: '',							name: 'Bye Week'})

jets.update_attributes(
	opp_week_1:	  buccaneers.id,
	opp_week_2:   patriots.id,
	opp_week_3:   bills.id,
	opp_week_4:   titans.id,
	opp_week_5:   falcons.id,
	opp_week_6:   steelers.id,
	opp_week_7:   patriots.id,
	opp_week_8:   bengals.id,
	opp_week_9:   saints.id,
	opp_week_10:  bye.id,
	opp_week_11:  bills.id,
	opp_week_12:  ravens.id,
	opp_week_13:  dolphins.id,
	opp_week_14:  raiders.id,
	opp_week_15:  panthers.id,
	opp_week_16:  browns.id,
	opp_week_17:  dolphins.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  false,
	home_week_6:  true,
	home_week_7:  true,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: true,
	home_week_11: false,
	home_week_12: false,
	home_week_13: true,
	home_week_14: true,
	home_week_15: false,
	home_week_16: true,
	home_week_17: false
	)

dolphins.update_attributes(
	opp_week_1:	  browns.id,
	opp_week_2:   colts.id,
	opp_week_3:   falcons.id,
	opp_week_4:   saints.id,
	opp_week_5:   ravens.id,
	opp_week_6:   bye.id,
	opp_week_7:   bills.id,
	opp_week_8:   patriots.id,
	opp_week_9:   bengals.id,
	opp_week_10:  buccaneers.id,
	opp_week_11:  chargers.id,
	opp_week_12:  panthers.id,
	opp_week_13:  jets.id,
	opp_week_14:  steelers.id,
	opp_week_15:  patriots.id,
	opp_week_16:  bills.id,
	opp_week_17:  jets.id,
	home_week_1:  false,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  true,
	home_week_6:  true,
	home_week_7:  true,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: true,
	home_week_12: true,
	home_week_13: false,
	home_week_14: false,
	home_week_15: true,
	home_week_16: false,
	home_week_17: true
	)

patriots.update_attributes(
	opp_week_1:	  bills.id,
	opp_week_2:   jets.id,
	opp_week_3:   buccaneers.id,
	opp_week_4:   falcons.id,
	opp_week_5:   bengals.id,
	opp_week_6:   saints.id,
	opp_week_7:   jets.id,
	opp_week_8:   dolphins.id,
	opp_week_9:   steelers.id,
	opp_week_10:  bye.id,
	opp_week_11:  panthers.id,
	opp_week_12:  broncos.id,
	opp_week_13:  texans.id,
	opp_week_14:  browns.id,
	opp_week_15:  dolphins.id,
	opp_week_16:  ravens.id,
	opp_week_17:  bills.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  false,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  true,
	home_week_9:  true,
	home_week_10: true,
	home_week_11: false,
	home_week_12: true,
	home_week_13: false,
	home_week_14: true,
	home_week_15: false,
	home_week_16: false,
	home_week_17: true
	)

bills.update_attributes(
	opp_week_1:	  patriots.id,
	opp_week_2:   panthers.id,
	opp_week_3:   jets.id,
	opp_week_4:   ravens.id,
	opp_week_5:   browns.id,
	opp_week_6:   bengals.id,
	opp_week_7:   dolphins.id,
	opp_week_8:   saints.id,
	opp_week_9:   chiefs.id,
	opp_week_10:  steelers.id,
	opp_week_11:  jets.id,
	opp_week_12:  bye.id,
	opp_week_13:  falcons.id,
	opp_week_14:  buccaneers.id,
	opp_week_15:  jaguars.id,
	opp_week_16:  dolphins.id,
	opp_week_17:  patriots.id,
	home_week_1:  true,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  false,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: true,
	home_week_12: true,
	home_week_13: true,
	home_week_14: false,
	home_week_15: false,
	home_week_16: true,
	home_week_17: false
	)

giants.update_attributes(
	opp_week_1:	  cowboys.id,
	opp_week_2:   broncos.id,
	opp_week_3:   panthers.id,
	opp_week_4:   chiefs.id,
	opp_week_5:   eagles.id,
	opp_week_6:   bears.id,
	opp_week_7:   vikings.id,
	opp_week_8:   eagles.id,
	opp_week_9:   bye.id,
	opp_week_10:  raiders.id,
	opp_week_11:  packers.id,
	opp_week_12:  cowboys.id,
	opp_week_13:  redskins.id,
	opp_week_14:  chargers.id,
	opp_week_15:  seahawks.id,
	opp_week_16:  lions.id,
	opp_week_17:  redskins.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  false,
	home_week_5:  true,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: true,
	home_week_11: true,
	home_week_12: true,
	home_week_13: false,
	home_week_14: false,
	home_week_15: true,
	home_week_16: false,
	home_week_17: true
	)

eagles.update_attributes(
	opp_week_1:	  redskins.id,
	opp_week_2:   chargers.id,
	opp_week_3:   chiefs.id,
	opp_week_4:   broncos.id,
	opp_week_5:   giants.id,
	opp_week_6:   buccaneers.id,
	opp_week_7:   cowboys.id,
	opp_week_8:   giants.id,
	opp_week_9:   raiders.id,
	opp_week_10:  packers.id,
	opp_week_11:  redskins.id,
	opp_week_12:  bye.id,
	opp_week_13:  cardinals.id,
	opp_week_14:  lions.id,
	opp_week_15:  vikings.id,
	opp_week_16:  bears.id,
	opp_week_17:  cowboys.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  false,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  true,
	home_week_9:  false,
	home_week_10: false,
	home_week_11: true,
	home_week_12: true,
	home_week_13: true,
	home_week_14: true,
	home_week_15: false,
	home_week_16: true,
	home_week_17: false
	)

cowboys.update_attributes(
	opp_week_1:	  giants.id,
	opp_week_2:   chiefs.id,
	opp_week_3:   rams.id,
	opp_week_4:   chargers.id,
	opp_week_5:   broncos.id,
	opp_week_6:   redskins.id,
	opp_week_7:   eagles.id,
	opp_week_8:   lions.id,
	opp_week_9:   vikings.id,
	opp_week_10:  saints.id,
	opp_week_11:  bye.id,
	opp_week_12:  giants.id,
	opp_week_13:  raiders.id,
	opp_week_14:  bears.id,
	opp_week_15:  packers.id,
	opp_week_16:  redskins.id,
	opp_week_17:  eagles.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  true,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: true,
	home_week_12: false,
	home_week_13: true,
	home_week_14: false,
	home_week_15: true,
	home_week_16: false,
	home_week_17: true
	)

redskins.update_attributes(
	opp_week_1:	  eagles.id,
	opp_week_2:   packers.id,
	opp_week_3:   lions.id,
	opp_week_4:   raiders.id,
	opp_week_5:   bye.id,
	opp_week_6:   cowboys.id,
	opp_week_7:   bears.id,
	opp_week_8:   broncos.id,
	opp_week_9:   chargers.id,
	opp_week_10:  vikings.id,
	opp_week_11:  eagles.id,
	opp_week_12:  fortyniners.id,
	opp_week_13:  giants.id,
	opp_week_14:  chiefs.id,
	opp_week_15:  falcons.id,
	opp_week_16:  cowboys.id,
	opp_week_17:  giants.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  true,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: false,
	home_week_12: true,
	home_week_13: true,
	home_week_14: true,
	home_week_15: false,
	home_week_16: true,
	home_week_17: false
	)

steelers.update_attributes(
	opp_week_1:	  titans.id,
	opp_week_2:   bengals.id,
	opp_week_3:   bears.id,
	opp_week_4:   vikings.id,
	opp_week_5:   bye.id,
	opp_week_6:   jets.id,
	opp_week_7:   ravens.id,
	opp_week_8:   raiders.id,
	opp_week_9:   patriots.id,
	opp_week_10:  bills.id,
	opp_week_11:  lions.id,
	opp_week_12:  browns.id,
	opp_week_13:  ravens.id,
	opp_week_14:  dolphins.id,
	opp_week_15:  bengals.id,
	opp_week_16:  packers.id,
	opp_week_17:  browns.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  true,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  false,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: true,
	home_week_12: false,
	home_week_13: false,
	home_week_14: true,
	home_week_15: true,
	home_week_16: false,
	home_week_17: true
	)

bengals.update_attributes(
	opp_week_1:	  titans.id,
	opp_week_2:   bengals.id,
	opp_week_3:   bears.id,
	opp_week_4:   vikings.id,
	opp_week_5:   bye.id,
	opp_week_6:   jets.id,
	opp_week_7:   ravens.id,
	opp_week_8:   raiders.id,
	opp_week_9:   patriots.id,
	opp_week_10:  bills.id,
	opp_week_11:  lions.id,
	opp_week_12:  browns.id,
	opp_week_13:  ravens.id,
	opp_week_14:  dolphins.id,
	opp_week_15:  bengals.id,
	opp_week_16:  packers.id,
	opp_week_17:  browns.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  true,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  false,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: true,
	home_week_12: false,
	home_week_13: false,
	home_week_14: true,
	home_week_15: true,
	home_week_16: false,
	home_week_17: true
	)

browns.update_attributes(
	opp_week_1:	  dolphins.id,
	opp_week_2:   ravens.id,
	opp_week_3:   vikings.id,
	opp_week_4:   bengals.id,
	opp_week_5:   bills.id,
	opp_week_6:   lions.id,
	opp_week_7:   packers.id,
	opp_week_8:   chiefs.id,
	opp_week_9:   ravens.id,
	opp_week_10:  bye.id,
	opp_week_11:  bengals.id,
	opp_week_12:  steelers.id,
	opp_week_13:  jaguars.id,
	opp_week_14:  patriots.id,
	opp_week_15:  bears.id,
	opp_week_16:  jets.id,
	opp_week_17:  steelers.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  true,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: true,
	home_week_11: false,
	home_week_12: true,
	home_week_13: true,
	home_week_14: false,
	home_week_15: true,
	home_week_16: false,
	home_week_17: false
	)

ravens.update_attributes(
	opp_week_1:	  broncos.id,
	opp_week_2:   browns.id,
	opp_week_3:   texans.id,
	opp_week_4:   bills.id,
	opp_week_5:   dolphins.id,
	opp_week_6:   packers.id,
	opp_week_7:   steelers.id,
	opp_week_8:   bye.id,
	opp_week_9:   browns.id,
	opp_week_10:  bengals.id,
	opp_week_11:  bears.id,
	opp_week_12:  jets.id,
	opp_week_13:  steelers.id,
	opp_week_14:  vikings.id,
	opp_week_15:  lions.id,
	opp_week_16:  patriots.id,
	opp_week_17:  bengals.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  false,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  true,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: false,
	home_week_12: true,
	home_week_13: true,
	home_week_14: true,
	home_week_15: false,
	home_week_16: true,
	home_week_17: false
	)

packers.update_attributes(
	opp_week_1:	  fortyniners.id,
	opp_week_2:   redskins.id,
	opp_week_3:   bengals.id,
	opp_week_4:   bye.id,
	opp_week_5:   lions.id,
	opp_week_6:   ravens.id,
	opp_week_7:   browns.id,
	opp_week_8:   vikings.id,
	opp_week_9:   bears.id,
	opp_week_10:  eagles.id,
	opp_week_11:  giants.id,
	opp_week_12:  vikings.id,
	opp_week_13:  lions.id,
	opp_week_14:  falcons.id,
	opp_week_15:  cowboys.id,
	opp_week_16:  steelers.id,
	opp_week_17:  bears.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  true,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: true,
	home_week_11: false,
	home_week_12: true,
	home_week_13: false,
	home_week_14: true,
	home_week_15: false,
	home_week_16: true,
	home_week_17: false
	)

bears.update_attributes(
	opp_week_1:	  bengals.id,
	opp_week_2:   vikings.id,
	opp_week_3:   steelers.id,
	opp_week_4:   lions.id,
	opp_week_5:   saints.id,
	opp_week_6:   giants.id,
	opp_week_7:   redskins.id,
	opp_week_8:   bye.id,
	opp_week_9:   packers.id,
	opp_week_10:  lions.id,
	opp_week_11:  ravens.id,
	opp_week_12:  rams.id,
	opp_week_13:  vikings.id,
	opp_week_14:  cowboys.id,
	opp_week_15:  browns.id,
	opp_week_16:  eagles.id,
	opp_week_17:  packers.id,
	home_week_1:  true,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  false,
	home_week_5:  true,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  true,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: true,
	home_week_12: false,
	home_week_13: false,
	home_week_14: true,
	home_week_15: false,
	home_week_16: false,
	home_week_17: true
	)

lions.update_attributes(
	opp_week_1:	  vikings.id,
	opp_week_2:   cardinals.id,
	opp_week_3:   redskins.id,
	opp_week_4:   bears.id,
	opp_week_5:   packers.id,
	opp_week_6:   browns.id,
	opp_week_7:   bengals.id,
	opp_week_8:   cowboys.id,
	opp_week_9:   bye.id,
	opp_week_10:  bears.id,
	opp_week_11:  steelers.id,
	opp_week_12:  buccaneers.id,
	opp_week_13:  packers.id,
	opp_week_14:  eagles.id,
	opp_week_15:  ravens.id,
	opp_week_16:  giants.id,
	opp_week_17:  vikings.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  false,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  true,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: false,
	home_week_12: true,
	home_week_13: true,
	home_week_14: false,
	home_week_15: true,
	home_week_16: true,
	home_week_17: false
	)

vikings.update_attributes(
	opp_week_1:	  lions.id,
	opp_week_2:   bears.id,
	opp_week_3:   browns.id,
	opp_week_4:   steelers.id,
	opp_week_5:   bye.id,
	opp_week_6:   panthers.id,
	opp_week_7:   giants.id,
	opp_week_8:   packers.id,
	opp_week_9:   cowboys.id,
	opp_week_10:  redskins.id,
	opp_week_11:  seahawks.id,
	opp_week_12:  packers.id,
	opp_week_13:  bears.id,
	opp_week_14:  ravens.id,
	opp_week_15:  eagles.id,
	opp_week_16:  bengals.id,
	opp_week_17:  lions.id,
	home_week_1:  false,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  true,
	home_week_5:  true,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  true,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: false,
	home_week_12: false,
	home_week_13: true,
	home_week_14: false,
	home_week_15: true,
	home_week_16: false,
	home_week_17: true
	)

colts.update_attributes(
	opp_week_1:	  raiders.id,
	opp_week_2:   dolphins.id,
	opp_week_3:   fortyniners.id,
	opp_week_4:   jaguars.id,
	opp_week_5:   seahawks.id,
	opp_week_6:   chargers.id,
	opp_week_7:   broncos.id,
	opp_week_8:   bye.id,
	opp_week_9:   texans.id,
	opp_week_10:  rams.id,
	opp_week_11:  titans.id,
	opp_week_12:  cardinals.id,
	opp_week_13:  titans.id,
	opp_week_14:  bengals.id,
	opp_week_15:  texans.id,
	opp_week_16:  chiefs.id,
	opp_week_17:  jaguars.id,
	home_week_1:  true,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  false,
	home_week_5:  true,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  true,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: false,
	home_week_12: false,
	home_week_13: true,
	home_week_14: false,
	home_week_15: true,
	home_week_16: false,
	home_week_17: true
	)

jaguars.update_attributes(
	opp_week_1:	  chiefs.id,
	opp_week_2:   raiders.id,
	opp_week_3:   seahawks.id,
	opp_week_4:   colts.id,
	opp_week_5:   rams.id,
	opp_week_6:   broncos.id,
	opp_week_7:   chargers.id,
	opp_week_8:   fortyniners.id,
	opp_week_9:   bye.id,
	opp_week_10:  titans.id,
	opp_week_11:  cardinals.id,
	opp_week_12:  texans.id,
	opp_week_13:  browns.id,
	opp_week_14:  texans.id,
	opp_week_15:  bills.id,
	opp_week_16:  titans.id,
	opp_week_17:  colts.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  false,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  true,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: true,
	home_week_12: false,
	home_week_13: false,
	home_week_14: true,
	home_week_15: true,
	home_week_16: true,
	home_week_17: false
	)

titans.update_attributes(
	opp_week_1:	  steelers.id,
	opp_week_2:   texans.id,
	opp_week_3:   chargers.id,
	opp_week_4:   jets.id,
	opp_week_5:   chiefs.id,
	opp_week_6:   seahawks.id,
	opp_week_7:   fortyniners.id,
	opp_week_8:   bye.id,
	opp_week_9:   rams.id,
	opp_week_10:  jaguars.id,
	opp_week_11:  colts.id,
	opp_week_12:  raiders.id,
	opp_week_13:  colts.id,
	opp_week_14:  broncos.id,
	opp_week_15:  cardinals.id,
	opp_week_16:  jaguars.id,
	opp_week_17:  texans.id,
	home_week_1:  false,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  true,
	home_week_5:  true,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  true,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: true,
	home_week_12: false,
	home_week_13: false,
	home_week_14: false,
	home_week_15: true,
	home_week_16: false,
	home_week_17: true
	)

texans.update_attributes(
	opp_week_1:	  chargers.id,
	opp_week_2:   titans.id,
	opp_week_3:   ravens.id,
	opp_week_4:   seahawks.id,
	opp_week_5:   fortyniners.id,
	opp_week_6:   rams.id,
	opp_week_7:   chiefs.id,
	opp_week_8:   bye.id,
	opp_week_9:   colts.id,
	opp_week_10:  cardinals.id,
	opp_week_11:  raiders.id,
	opp_week_12:  jaguars.id,
	opp_week_13:  patriots.id,
	opp_week_14:  jaguars.id,
	opp_week_15:  colts.id,
	opp_week_16:  broncos.id,
	opp_week_17:  titans.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  false,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  true,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: true,
	home_week_12: true,
	home_week_13: true,
	home_week_14: false,
	home_week_15: false,
	home_week_16: true,
	home_week_17: false
	)

buccaneers.update_attributes(
	opp_week_1:	  jets.id,
	opp_week_2:   saints.id,
	opp_week_3:   patriots.id,
	opp_week_4:   cardinals.id,
	opp_week_5:   bye.id,
	opp_week_6:   eagles.id,
	opp_week_7:   falcons.id,
	opp_week_8:   panthers.id,
	opp_week_9:   seahawks.id,
	opp_week_10:  dolphins.id,
	opp_week_11:  falcons.id,
	opp_week_12:  lions.id,
	opp_week_13:  panthers.id,
	opp_week_14:  bills.id,
	opp_week_15:  fortyniners.id,
	opp_week_16:  rams.id,
	opp_week_17:  saints.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  true,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  true,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: true,
	home_week_12: false,
	home_week_13: false,
	home_week_14: true,
	home_week_15: true,
	home_week_16: false,
	home_week_17: false
	)

falcons.update_attributes(
	opp_week_1:	  saints.id,
	opp_week_2:   rams.id,
	opp_week_3:   dolphins.id,
	opp_week_4:   patriots.id,
	opp_week_5:   jets.id,
	opp_week_6:   bye.id,
	opp_week_7:   buccaneers.id,
	opp_week_8:   cardinals.id,
	opp_week_9:   panthers.id,
	opp_week_10:  seahawks.id,
	opp_week_11:  buccaneers.id,
	opp_week_12:  saints.id,
	opp_week_13:  bills.id,
	opp_week_14:  packers.id,
	opp_week_15:  redskins.id,
	opp_week_16:  fortyniners.id,
	opp_week_17:  panthers.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  true,
	home_week_6:  true,
	home_week_7:  true,
	home_week_8:  false,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: false,
	home_week_12: true,
	home_week_13: false,
	home_week_14: false,
	home_week_15: true,
	home_week_16: false,
	home_week_17: true
	)

saints.update_attributes(
	opp_week_1:	  falcons.id,
	opp_week_2:   buccaneers.id,
	opp_week_3:   cardinals.id,
	opp_week_4:   dolphins.id,
	opp_week_5:   bears.id,
	opp_week_6:   patriots.id,
	opp_week_7:   bye.id,
	opp_week_8:   bills.id,
	opp_week_9:   jets.id,
	opp_week_10:  cowboys.id,
	opp_week_11:  fortyniners.id,
	opp_week_12:  falcons.id,
	opp_week_13:  seahawks.id,
	opp_week_14:  panthers.id,
	opp_week_15:  rams.id,
	opp_week_16:  panthers.id,
	opp_week_17:  buccaneers.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  true,
	home_week_5:  false,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  true,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: true,
	home_week_12: false,
	home_week_13: false,
	home_week_14: true,
	home_week_15: false,
	home_week_16: false,
	home_week_17: true
	)

panthers.update_attributes(
	opp_week_1:	  seahawks.id,
	opp_week_2:   bills.id,
	opp_week_3:   giants.id,
	opp_week_4:   bye.id,
	opp_week_5:   cardinals.id,
	opp_week_6:   vikings.id,
	opp_week_7:   rams.id,
	opp_week_8:   buccaneers.id,
	opp_week_9:   falcons.id,
	opp_week_10:  fortyniners.id,
	opp_week_11:  patriots.id,
	opp_week_12:  dolphins.id,
	opp_week_13:  buccaneers.id,
	opp_week_14:  saints.id,
	opp_week_15:  jets.id,
	opp_week_16:  saints.id,
	opp_week_17:  falcons.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  true,
	home_week_5:  false,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: true,
	home_week_12: false,
	home_week_13: true,
	home_week_14: false,
	home_week_15: true,
	home_week_16: true,
	home_week_17: false
	)

chiefs.update_attributes(
	opp_week_1:	  jaguars.id,
	opp_week_2:   cowboys.id,
	opp_week_3:   eagles.id,
	opp_week_4:   giants.id,
	opp_week_5:   titans.id,
	opp_week_6:   raiders.id,
	opp_week_7:   texans.id,
	opp_week_8:   browns.id,
	opp_week_9:   bills.id,
	opp_week_10:  bye.id,
	opp_week_11:  broncos.id,
	opp_week_12:  chargers.id,
	opp_week_13:  broncos.id,
	opp_week_14:  redskins.id,
	opp_week_15:  raiders.id,
	opp_week_16:  colts.id,
	opp_week_17:  chargers.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  false,
	home_week_6:  true,
	home_week_7:  true,
	home_week_8:  true,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: false,
	home_week_12: true,
	home_week_13: true,
	home_week_14: false,
	home_week_15: false,
	home_week_16: true,
	home_week_17: false
	)

broncos.update_attributes(
	opp_week_1:	  ravens.id,
	opp_week_2:   giants.id,
	opp_week_3:   raiders.id,
	opp_week_4:   eagles.id,
	opp_week_5:   cowboys.id,
	opp_week_6:   jaguars.id,
	opp_week_7:   colts.id,
	opp_week_8:   redskins.id,
	opp_week_9:   bye.id,
	opp_week_10:  chargers.id,
	opp_week_11:  chiefs.id,
	opp_week_12:  patriots.id,
	opp_week_13:  chiefs.id,
	opp_week_14:  titans.id,
	opp_week_15:  chargers.id,
	opp_week_16:  texans.id,
	opp_week_17:  raiders.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  true,
	home_week_5:  false,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  true,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: true,
	home_week_12: false,
	home_week_13: false,
	home_week_14: true,
	home_week_15: true,
	home_week_16: false,
	home_week_17: false
	)

chargers.update_attributes(
	opp_week_1:	  texans.id,
	opp_week_2:   eagles.id,
	opp_week_3:   titans.id,
	opp_week_4:   cowboys.id,
	opp_week_5:   raiders.id,
	opp_week_6:   colts.id,
	opp_week_7:   jaguars.id,
	opp_week_8:   bye.id,
	opp_week_9:   redskins.id,
	opp_week_10:  broncos.id,
	opp_week_11:  dolphins.id,
	opp_week_12:  chiefs.id,
	opp_week_13:  bengals.id,
	opp_week_14:  giants.id,
	opp_week_15:  broncos.id,
	opp_week_16:  raiders.id,
	opp_week_17:  chiefs.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  false,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  true,
	home_week_9:  false,
	home_week_10: true,
	home_week_11: false,
	home_week_12: false,
	home_week_13: true,
	home_week_14: true,
	home_week_15: false,
	home_week_16: true,
	home_week_17: true
	)

raiders.update_attributes(
	opp_week_1:	  colts.id,
	opp_week_2:   jaguars.id,
	opp_week_3:   broncos.id,
	opp_week_4:   redskins.id,
	opp_week_5:   chargers.id,
	opp_week_6:   chiefs.id,
	opp_week_7:   bye.id,
	opp_week_8:   steelers.id,
	opp_week_9:   eagles.id,
	opp_week_10:  giants.id,
	opp_week_11:  texans.id,
	opp_week_12:  titans.id,
	opp_week_13:  cowboys.id,
	opp_week_14:  jets.id,
	opp_week_15:  chiefs.id,
	opp_week_16:  chargers.id,
	opp_week_17:  broncos.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  true,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  true,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: false,
	home_week_12: true,
	home_week_13: false,
	home_week_14: false,
	home_week_15: true,
	home_week_16: false,
	home_week_17: true
	)

fortyniners.update_attributes(
	opp_week_1:	  packers.id,
	opp_week_2:   seahawks.id,
	opp_week_3:   colts.id,
	opp_week_4:   rams.id,
	opp_week_5:   texans.id,
	opp_week_6:   cardinals.id,
	opp_week_7:   titans.id,
	opp_week_8:   jaguars.id,
	opp_week_9:   bye.id,
	opp_week_10:  panthers.id,
	opp_week_11:  saints.id,
	opp_week_12:  redskins.id,
	opp_week_13:  rams.id,
	opp_week_14:  seahawks.id,
	opp_week_15:  buccaneers.id,
	opp_week_16:  falcons.id,
	opp_week_17:  cardinals.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  true,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: true,
	home_week_11: false,
	home_week_12: false,
	home_week_13: true,
	home_week_14: true,
	home_week_15: false,
	home_week_16: true,
	home_week_17: false
	)

seahawks.update_attributes(
	opp_week_1:	  panthers.id,
	opp_week_2:   fortyniners.id,
	opp_week_3:   jaguars.id,
	opp_week_4:   texans.id,
	opp_week_5:   colts.id,
	opp_week_6:   titans.id,
	opp_week_7:   cardinals.id,
	opp_week_8:   rams.id,
	opp_week_9:   buccaneers.id,
	opp_week_10:  falcons.id,
	opp_week_11:  vikings.id,
	opp_week_12:  bye.id,
	opp_week_13:  saints.id,
	opp_week_14:  fortyniners.id,
	opp_week_15:  giants.id,
	opp_week_16:  cardinals.id,
	opp_week_17:  rams.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  true,
	home_week_4:  false,
	home_week_5:  false,
	home_week_6:  true,
	home_week_7:  false,
	home_week_8:  false,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: true,
	home_week_12: true,
	home_week_13: true,
	home_week_14: false,
	home_week_15: false,
	home_week_16: true,
	home_week_17: true
	)

rams.update_attributes(
	opp_week_1:	  cardinals.id,
	opp_week_2:   falcons.id,
	opp_week_3:   cowboys.id,
	opp_week_4:   fortyniners.id,
	opp_week_5:   jaguars.id,
	opp_week_6:   texans.id,
	opp_week_7:   panthers.id,
	opp_week_8:   seahawks.id,
	opp_week_9:   titans.id,
	opp_week_10:  colts.id,
	opp_week_11:  bye.id,
	opp_week_12:  bears.id,
	opp_week_13:  fortyniners.id,
	opp_week_14:  cardinals.id,
	opp_week_15:  saints.id,
	opp_week_16:  buccaneers.id,
	opp_week_17:  seahawks.id,
	home_week_1:  true,
	home_week_2:  false,
	home_week_3:  false,
	home_week_4:  true,
	home_week_5:  true,
	home_week_6:  false,
	home_week_7:  false,
	home_week_8:  true,
	home_week_9:  true,
	home_week_10: false,
	home_week_11: true,
	home_week_12: true,
	home_week_13: false,
	home_week_14: false,
	home_week_15: true,
	home_week_16: true,
	home_week_17: false
	)

cardinals.update_attributes(
	opp_week_1:	  rams.id,
	opp_week_2:   lions.id,
	opp_week_3:   saints.id,
	opp_week_4:   buccaneers.id,
	opp_week_5:   panthers.id,
	opp_week_6:   fortyniners.id,
	opp_week_7:   seahawks.id,
	opp_week_8:   falcons.id,
	opp_week_9:   bye.id,
	opp_week_10:  texans.id,
	opp_week_11:  jaguars.id,
	opp_week_12:  colts.id,
	opp_week_13:  eagles.id,
	opp_week_14:  rams.id,
	opp_week_15:  titans.id,
	opp_week_16:  seahawks.id,
	opp_week_17:  fortyniners.id,
	home_week_1:  false,
	home_week_2:  true,
	home_week_3:  false,
	home_week_4:  false,
	home_week_5:  true,
	home_week_6:  false,
	home_week_7:  true,
	home_week_8:  true,
	home_week_9:  true,
	home_week_10: true,
	home_week_11: false,
	home_week_12: true,
	home_week_13: false,
	home_week_14: true,
	home_week_15: false,
	home_week_16: false,
	home_week_17: true
	)




players = Player.create([
	{last_name: 'Powell',			first_name: 'Bilal',			team_id: jets.id,					position: 'RB'},
	{last_name: 'Ivory',			first_name: 'Chris',			team_id: jets.id,					position: 'RB'},
	{last_name: 'Miller',			first_name: 'Lamar',			team_id: dolphins.id,			position: 'RB'},
	{last_name: 'Ridley',			first_name: 'Stevan',			team_id: patriots.id,			position: 'RB'},
	{last_name: 'Vereen',			first_name: 'Shane',			team_id: patriots.id,			position: 'RB'},
	{last_name: 'Jackson',		first_name: 'Fred',				team_id: bills.id,				position: 'RB'},
	{last_name: 'Spiller',		first_name: 'C.J.',				team_id: bills.id,				position: 'RB'},
	{last_name: 'Wilson',			first_name: 'David',			team_id: giants.id,				position: 'RB'},
	{last_name: 'Hillis',			first_name: 'Peyton',			team_id: giants.id,				position: 'RB'},
	{last_name: 'McCoy',			first_name: 'Lesean',			team_id: eagles.id,				position: 'RB'},
	{last_name: 'Murray',			first_name: 'DeMarco',		team_id: cowboys.id,			position: 'RB'},
	{last_name: 'Morris',			first_name: 'Alfred',			team_id: redskins.id,			position: 'RB'},
	{last_name: 'Helu',				first_name: 'Roy',				team_id: redskins.id,			position: 'RB'},
	{last_name: 'Bell',				first_name: 'LeVeon',			team_id: steelers.id,			position: 'RB'},
	{last_name: 'Dwyer',			first_name: 'Jonathan',		team_id: steelers.id,			position: 'RB'},
	{last_name: 'Green-Ellis',first_name: 'Ben Jarvus',	team_id: bengals.id,			position: 'RB'},
	{last_name: 'Bernard',		first_name: 'Giovani',		team_id: bengals.id,			position: 'RB'},
	{last_name: 'McGahee',		first_name: 'Willis',			team_id: bengals.id,			position: 'RB'},
	{last_name: 'Rice',				first_name: 'Ray',				team_id: ravens.id,				position: 'RB'},
	{last_name: 'Starks',			first_name: 'James',			team_id: packers.id,			position: 'RB'},
	{last_name: 'Lacy',				first_name: 'Eddie',			team_id: packers.id,			position: 'RB'},
	{last_name: 'Forte',			first_name: 'Matt',				team_id: bears.id,				position: 'RB'},
	{last_name: 'Bush',				first_name: 'Reggie',			team_id: lions.id,				position: 'RB'},
	{last_name: 'Bell',				first_name: 'Joique',			team_id: lions.id,				position: 'RB'},
	{last_name: 'Peterson', 	first_name: 'Adrian', 		team_id: vikings.id,			position: 'RB'},
	{last_name: 'Richardson',	first_name: 'Trent',			team_id: colts.id,				position: 'RB'},
	{last_name: 'Jones-Drew',	first_name: 'Maurice',		team_id: jaguars.id,			position: 'RB'},
	{last_name: 'Johnson',		first_name: 'Chris',			team_id: titans.id,				position: 'RB'},
	{last_name: 'Foster',			first_name: 'Arian',			team_id: texans.id,				position: 'RB'},
	{last_name: 'Tate',				first_name: 'Ben',				team_id: texans.id,				position: 'RB'},
	{last_name: 'Martin',			first_name: 'Doug',				team_id: buccaneers.id,		position: 'RB'},
	{last_name: 'James',			first_name: 'Mike',				team_id: buccaneers.id,		position: 'RB'},
	{last_name: 'Jackson',		first_name: 'Steven',			team_id: falcons.id,			position: 'RB'},
	{last_name: 'Rodgers',		first_name: 'Jacquizz',		team_id: falcons.id,			position: 'RB'},
	{last_name: 'Sproles',		first_name: 'Darren',			team_id: saints.id,				position: 'RB'},
	{last_name: 'Thomas',			first_name: 'Pierre',			team_id: saints.id,				position: 'RB'},
	{last_name: 'Williams',		first_name: 'DeAngelo',		team_id: panthers.id,			position: 'RB'},
	{last_name: 'Charles',		first_name: 'Jamaal',			team_id: chiefs.id,				position: 'RB'},
	{last_name: 'Moreno',			first_name: 'Knowshon',		team_id: broncos.id,			position: 'RB'},
	{last_name: 'Matthews',		first_name: 'Ryan',				team_id: chargers.id,			position: 'RB'},
	{last_name: 'McFadden',		first_name: 'Darren',			team_id: raiders.id,			position: 'RB'},
	{last_name: 'Gore', 			first_name: 'Frank', 			team_id: fortyniners.id,	position: 'RB'},
	{last_name: 'Lynch',			first_name: 'Marshawn',		team_id: seahawks.id,			position: 'RB'},
	{last_name: 'Richardson',	first_name: 'Daryl',			team_id: rams.id,					position: 'RB'},
	{last_name: 'Stacy',			first_name: 'Zac',				team_id: rams.id,					position: 'RB'},
	{last_name: 'Mendenhall',	first_name: 'Rashard',		team_id: cardinals.id,		position: 'RB'},
	{last_name: 'Ellington',	first_name: 'Andre',			team_id: cardinals.id,		position: 'RB'},
	{last_name: 'Williams',		first_name: 'Ryan',				team_id: cardinals.id,		position: 'RB'}
	])

admin =	User.create(name: 'Jason Ackerman',		email: 'jackerman09@gmail.com', password: 'railstutorial', password_confirmation: 'railstutorial', admin: true)
user =	User.create(name: 'Jessica Smagler',	email: 'jbsmags@aol.com', 			password: 'railstutorial', password_confirmation: 'railstutorial', admin: false)

players = Player.all
matchups = []
players.each do |player1|
	players.each do |player2|
		exists = Matchup.find_by(player_1: player1.id, player_2: player2.id) || Matchup.find_by(player_1: player2.id, player_2: player1.id)
    if exists.nil?
			if player1.id != player2.id
				matchup = { player_1: player1.id, player_2: player2.id }
				matchups.push matchup
			end
		end
	end
end

Matchup.create(matchups)
